# Generated by Django 4.0 on 2021-12-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('IdDiagnostico', models.BigAutoField(primary_key=True, serialize=False)),
                ('Placa', models.CharField(max_length=100)),
                ('Cliente', models.CharField(max_length=100)),
                ('Fecha', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=13)),
                ('Estado', models.CharField(max_length=100)),
            ],
        ),
    ]
