# Generated by Django 4.0 on 2021-12-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDiagnostico',
            fields=[
                ('IdDetalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100)),
                ('Opcion', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('NumeroParte', models.CharField(max_length=13)),
                ('DetalleSolicitud', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='Detalles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.detallediagnostico'),
        ),
    ]
