# Generated by Django 4.0 on 2021-12-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0002_detallediagnostico_diagnosticos_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticos',
            name='Detalles',
        ),
    ]
