# Generated by Django 4.0 on 2021-12-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0003_remove_diagnosticos_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticos',
            name='Detalles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.detallediagnostico'),
        ),
    ]
